apiVersion: v1
kind: Service
metadata:
  name: flask-k8s-service
  labels:
    app: flask-k8s-app
spec:
  type: NodePort
  selector:
    app: flask-k8s-app
  ports:
    - name: http
      port: 80
      targetPort: 5000
      nodePort: 30080
